# Generated by Django 6.0.6 on 2026-07-12 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_user_profile_picture_user_profile_picture_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
