# Generated by Django 6.0.6 on 2026-07-12 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_room_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='profile_picture_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
